// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClhSx1mA0iwdw6DQmFd3Diz8IJwie3Lhk',
    appId: '1:451246976546:web:a8697b08e03fe5a0ed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    authDomain: 'seretei8.firebaseapp.com',
    databaseURL: 'https://seretei8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seretei8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHAurQBhbY3gEfqV19v7lcdoqM08dkUU',
    appId: '1:451246976546:android:bb073ccbf2529104ed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    databaseURL: 'https://seretei8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seretei8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9euc9kbRe3FXQBBhPLTQ41TkrBNig9c',
    appId: '1:451246976546:ios:6f57b39e43d5815eed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    databaseURL: 'https://seretei8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seretei8.firebasestorage.app',
    iosClientId: '451246976546-affgoqpbiugc72rskcisqg89fnotkojd.apps.googleusercontent.com',
    iosBundleId: 'com.example.motoguard',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9euc9kbRe3FXQBBhPLTQ41TkrBNig9c',
    appId: '1:451246976546:ios:6f57b39e43d5815eed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    databaseURL: 'https://seretei8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seretei8.firebasestorage.app',
    iosClientId: '451246976546-affgoqpbiugc72rskcisqg89fnotkojd.apps.googleusercontent.com',
    iosBundleId: 'com.example.motoguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClhSx1mA0iwdw6DQmFd3Diz8IJwie3Lhk',
    appId: '1:451246976546:web:dc15b8f80a309698ed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    authDomain: 'seretei8.firebaseapp.com',
    databaseURL: 'https://seretei8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seretei8.firebasestorage.app',
  );
}
